version: "3.0"
services:
    application:
        image: php:${PHP_VERSION}
        volumes:
            -
                type: bind
                source: .
                target: /application
        working_dir: /application
